FROM php:7.4-apache

# Install dependencies
RUN docker-php-ext-install pdo pdo_mysql

# Copy application source code to the container
COPY . /var/www/html/

# Set working directory
WORKDIR /var/www/html/

# Expose port 80
EXPOSE 80
